<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // データのクリア
        DB::table('products')->truncate();
        
        $param = [ 'name' => '酒饅頭（5個入り）', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '500', 'online_order_flg' => '0', 'img_url' => 'img/items/sakaman_5p.jpg', 'cold_delivery' => '0' ];
        DB::table('products')->insert($param);$param = [ 'name' => '酒饅頭（10個入り）', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,000', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '酒饅頭（15個入り）', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,410', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '酒饅頭（20個入り）', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,880', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '酒饅頭（30個入り）', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,750', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '葛ようかん', 'detail' => '若狭名物です。', 'category1' => '1', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '500', 'online_order_flg' => '1', 'img_url' => 'img/items/kuzuyokan.jpg', 'cold_delivery' => '1 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(プレーン)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/omaki_plane.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(いちご)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/omaki_ichigo.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(紅茶)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/omaki_koucha.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(抹茶)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/omaki_macha.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(夏みかん)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '2', 'category3' => '1', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/mikan.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'お巻き(バニラ)', 'detail' => '若狭名物です。', 'category1' => '3', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'ほうじ茶の葛とろプリン', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '200', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '黒蜜ふるーつあんみつ', 'detail' => '若狭名物です。', 'category1' => '1', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '380', 'online_order_flg' => '0', 'img_url' => 'img/items/anmistu.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '珈琲わらびもち', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '400', 'online_order_flg' => '0', 'img_url' => 'img/items/warabi_coffe.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '抹茶わらびもち', 'detail' => '若狭名物です。', 'category1' => '2', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '400', 'online_order_flg' => '0', 'img_url' => 'img/items/macha.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'まるごとりんごパイ', 'detail' => '若狭名物です。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'いちご大福', 'detail' => '若狭名物です。', 'category1' => '1', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '186', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'みかん大福', 'detail' => '若狭名物です。', 'category1' => '1', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '186', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '若狭かれい最中', 'detail' => '若狭の名物「若狭かれい」をかたどったモナカです。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '130', 'online_order_flg' => '0', 'img_url' => 'img/items/karei.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'くずまんじゅう', 'detail' => '若狭名物くずまんじゅう。', 'category1' => '1', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '500', 'online_order_flg' => '0', 'img_url' => 'img/items/kuzuman.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'ふくさ', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/fukusa.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '薯蕷まんじゅう', 'detail' => 'こしあんが入っています。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '140', 'online_order_flg' => '0', 'img_url' => 'img/items/chucho.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '田舎まんじゅう', 'detail' => 'つぶあんが入っています。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/inaka.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '沖の石', 'detail' => 'サクサクしたクッキー生地にバタークリームをはさんだ人気商品です！', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '150', 'online_order_flg' => '0', 'img_url' => 'img/items/okinoishi.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'どらやき', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/doarayaki.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'なみかげ', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/namikage.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '六方焼', 'detail' => 'こしあんが入っています。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/roppou.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'マドレーヌ', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/madorenu.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '酒蔵', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/sakagura.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'わらびもち', 'detail' => '若狭名物です。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '400', 'online_order_flg' => '0', 'img_url' => 'img/items/kinako.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '松風', 'detail' => 'つぶあんが入っています。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '茶通', 'detail' => 'つぶあんが入っています。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/chastu.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '栗まんじゅう', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '115', 'online_order_flg' => '0', 'img_url' => 'img/items/kurimanju.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '杏っ子', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/anzukko.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'カステラ', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '135', 'online_order_flg' => '0', 'img_url' => 'img/items/kasutera.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'クレームブリュレ', 'detail' => '若狭名物です。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '200', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '練り切り', 'detail' => '若狭名物です。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '167', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '赤飯(五合折)', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,200', 'online_order_flg' => '0', 'img_url' => 'img/items/sekihan.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '赤飯(三合折)', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '750', 'online_order_flg' => '0', 'img_url' => 'img/items/sekihan.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '赤飯(二合折)', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '500', 'online_order_flg' => '0', 'img_url' => 'img/items/sekihan.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '赤飯(一升)', 'detail' => '若狭名物です。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,400', 'online_order_flg' => '0', 'img_url' => 'img/items/sekihan.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '上用饅頭(2個入り)', 'detail' => '2個入り', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,000', 'online_order_flg' => '0', 'img_url' => 'img/items/jouyo_2p.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '上用饅頭(5個入り)', 'detail' => '5個入り', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,000', 'online_order_flg' => '0', 'img_url' => 'img/items/jouyo_5p.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '赤白餅まんじゅう(2個入り)', 'detail' => '2個入り', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,160', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '栗まんじゅう(栗入り)', 'detail' => '', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,000', 'online_order_flg' => '0', 'img_url' => 'img/items/kurimanju_kuriiri.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '引き菓子', 'detail' => '仏事も承ります。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '3,240', 'online_order_flg' => '0', 'img_url' => 'img/items/hikigashi.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '洋梨タルト', 'detail' => '2000～2500円？', 'category1' => '3', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,500', 'online_order_flg' => '0', 'img_url' => 'img/items/younashi.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'だんご', 'detail' => '若狭名物です。', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '700', 'online_order_flg' => '0', 'img_url' => 'img/items/dango.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'でっちちょうかん(5本入り)', 'detail' => '季節限定商品', 'category1' => '1', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '500', 'online_order_flg' => '1', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '1 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'でっちちょうかん(10本入り)', 'detail' => '季節限定商品', 'category1' => '1', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,150', 'online_order_flg' => '1', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '1 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'でっちちょうかん(18本入り)', 'detail' => '季節限定商品', 'category1' => '1', 'category2' => '2', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '2,000', 'online_order_flg' => '1', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '1 '];
        DB::table('products')->insert($param);$param = [ 'name' => 'たいこ饅頭(5個入り)', 'detail' => '白あん・こしあん', 'category1' => '', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,836', 'online_order_flg' => '0', 'img_url' => 'img/items/taiko.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '若狭小浜ぱんどじぇーぬ', 'detail' => '', 'category1' => '3', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,400', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '砂糖のお菓子(大)', 'detail' => '上白糖でできてますので、お正月の後も邪魔になりません。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '1,500', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '砂糖のお菓子(中)', 'detail' => '上白糖でできてますので、お正月の後も邪魔になりません。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '900', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);$param = [ 'name' => '砂糖のお菓子(小)', 'detail' => '上白糖でできてますので、お正月の後も邪魔になりません。', 'category1' => '4', 'category2' => '', 'category3' => '', 'category4' => '', 'category5' => '', 'price' => '600', 'online_order_flg' => '0', 'img_url' => 'img/items/.jpg', 'cold_delivery' => '0 '];
        DB::table('products')->insert($param);
    }
}
